require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/short_links", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ShortLink. As you add validations to ShortLink, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ShortLink.create! valid_attributes
      get short_links_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      short_link = ShortLink.create! valid_attributes
      get short_link_url(short_link)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_short_link_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      short_link = ShortLink.create! valid_attributes
      get edit_short_link_url(short_link)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ShortLink" do
        expect {
          post short_links_url, params: { short_link: valid_attributes }
        }.to change(ShortLink, :count).by(1)
      end

      it "redirects to the created short_link" do
        post short_links_url, params: { short_link: valid_attributes }
        expect(response).to redirect_to(short_link_url(ShortLink.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ShortLink" do
        expect {
          post short_links_url, params: { short_link: invalid_attributes }
        }.to change(ShortLink, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post short_links_url, params: { short_link: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested short_link" do
        short_link = ShortLink.create! valid_attributes
        patch short_link_url(short_link), params: { short_link: new_attributes }
        short_link.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the short_link" do
        short_link = ShortLink.create! valid_attributes
        patch short_link_url(short_link), params: { short_link: new_attributes }
        short_link.reload
        expect(response).to redirect_to(short_link_url(short_link))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        short_link = ShortLink.create! valid_attributes
        patch short_link_url(short_link), params: { short_link: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested short_link" do
      short_link = ShortLink.create! valid_attributes
      expect {
        delete short_link_url(short_link)
      }.to change(ShortLink, :count).by(-1)
    end

    it "redirects to the short_links list" do
      short_link = ShortLink.create! valid_attributes
      delete short_link_url(short_link)
      expect(response).to redirect_to(short_links_url)
    end
  end
end
